name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cd ./apps/opinion-ate/ && yarn install --frozen-lockfile
      - name: Unit Tests
        run: cd ./apps/opinion-ate/ && yarn test --watchAll=false
      - name: E2E Tests
        uses: cypress-io/github-action@v3.0.3
        with:
          start: cd ./apps/opinion-ate/ && yarn start
          wait-on: 'http://localhost:3000'